Rename line to port
darwinia-network/darwinia-msgport pull request #199
Opened 2024-01-26 06:02 UTC by hujw77

2024-01-30 02:58 UTC, hackfisher commented
@hujw77 The CI failed, would you please give a check?

2024-01-30 02:59 UTC, hackfisher commented on script/deploy/DeployORMPPort.s.sol
> +        ScriptTools.exportContract(outputName, "ORMP_port", ADDR);
why lower case here?

2024-01-30 03:24 UTC, jiguantong requested changes

2024-01-30 03:24 UTC, jiguantong commented on script/deploy/DeployPortRegistry.s.sol
> +        ADDR = c3.readAddress(".portREGISTRY_ADDR");
Upper case?

2024-01-30 03:24 UTC, jiguantong commented on script/deploy/DeployPortRegistry.s.sol
> +        SALT = c3.readBytes32(".portREGISTRY_SALT");
Upper case?

2024-01-30 03:24 UTC, jiguantong commented on src/PortRegistry.sol
> +/// @title PotRegistry
typo

2024-01-30 03:24 UTC, jiguantong commented on src/examples/ExampleReceiverDapp.sol
>      address public immutable LINE;
LINE => PORT

2024-01-30 03:24 UTC, jiguantong commented on src/examples/ExampleReceiverDapp.sol
> +        require(localPort == LINE);
LINE => PORT

2024-01-30 03:36 UTC, jiguantong commented
Missed to be updated    exclude(lib/**, out/**, .git/**, cache/**, output/**)
- [ ] *.md README & SUPPORTED
- [ ] *.sh add & config & dao
- [ ] *.json  ormp.json
- [ ] *.sol  xxChainIdMapping & ExampleReceiverDapp & GNSPSBytesLib

2024-01-31 03:47 UTC, jiguantong commented
https://github.com/darwinia-network/darwinia-msgport/blob/echo/r/script/input/c3.json
https://github.com/darwinia-network/darwinia-msgport/blob/echo/r/bin/add.sh

2024-01-31 06:16 UTC, hujw77 commented
> @hujw77 The CI failed, would you please give a check?

CI use mainnet Msgport addresses, would be fixed after mainnet deployed.

2024-01-31 06:35 UTC, jiguantong approved these changes

2024-01-31 07:32 UTC, hackfisher approved these changes

2024-02-01 09:00 UTC, merged